# Generated by Django 6.0 on 2025-12-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movieadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('movie_file', models.FileField(upload_to='movie/')),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
            ],
        ),
    ]
