# Generated by Django 6.0 on 2026-01-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0004_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieadd',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
